#!/usr/bin/env bash
#What type of network a computer in local is connected to
3
#what type of network could connect a office in one building to another office in a building a few streets away?
2
#what network do oyou use when you browse www.google.com from your smartphone (not conneced to the wifi)?
1
